version: "3.9"

services:
  angular_app:
    container_name: angular_app
    image: rentease-angular_app:1.0.0
    build: ./angular/RentEase-Front/
    ports:
      - 4200:4200
    depends_on:
      - java_app
  java_app:
    container_name: java_app
    image: rentease-java-app:1.0.0
    build: .
    ports:
      - 8081:8081
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/rentease
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=admin
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rentease
